spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      pool-name: HikariCP
      username: postgres
      password: admin
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        stat: DEBUG
        cache: DEBUG
