spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      pool-name: HikariCP
      username: postgres
      password: admin
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080